services:
  backend:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:   
        PHP_VERSION: "${PHP_VERSION}"
        NODE_VERSION: "${NODE_VERSION}"
    image: "${BACKEND_IMAGE}"
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ..:/workspace:cached
    environment:     
      MAILER_DSN: smtp://user:pass@mailpit:1025      
      DATABASE_URL: mysql://symfony:symfony@db:3306/${PROJECT_NAME}_db?serverVersion=8.0
    depends_on:
      - db     
      - mailpit
    networks:
      - app-network
    command: sleep infinity

  db:
    image: "${MYSQL_IMAGE}"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${PROJECT_NAME}_db"
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-network
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    networks:
      - app-network

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    ports:
      - "${MAILPIT_HTTP_PORT}:8025"
      - "${MAILPIT_SMTP_PORT}:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: devcontainer-network

volumes:
  db-data:
